### ISSUE TITLE
Shouldn't adonis-api-app template disabled by default csrf protection

### ISSUE THREAD

**Issue by mathieuh** [adonisjs/adonis-api-app#16]
Hi,
I think its far the most question asked on adonisjs gitter. A lot of people are confused with csrf and api-only app. Shouldn't csrf protection be disabled in this template? I'd be happy to fix it if its the proper behavior though I can't find any shield.js file in this template.

**Comment by RomainLanz** [comment]
Hey @mathieuh! 👋 

The main issue is people installing the default boilerplate of Adonis, which is the full stack one.
Since the full stack blueprint has the CSRF protection enable they must disable it.

If they want to create an API only they must use the `--api` flag while running `adonis new`.

**Comment by mathieuh** [comment]
Ok apparently it's just people using the full template instead of this one that is well configured already. My bad
