### ISSUE TITLE
EADDRINUSE when adonis is automatically reloaded.

### ISSUE THREAD

**Issue by renatomattos2912** [adonisjs/adonis-api-app#17]
Hi,

I'm using:
MacOS 10.12.6
NodeJS 8.9.0
Adonis 4.0 API Only blueprint

The problem is:
When i start the adonis using command "adonis serve --dev", adonis is started successfully, but when i make some code changes and adonis automatically reloads, the adonis crash and show me the error EADDRINUSE. It is like adonis try to reload but do not stop the instance correctly, so they try to restart without kill the process, and it causes an issue with port in use.

See the print bellow:
![screen shot 2018-02-05 at 10 25 04](https://user-images.githubusercontent.com/2312835/35804899-d791e1ce-0a60-11e8-88f5-47d7351acfcb.png)

Can you help me to solve this issue?

**Comment by renatomattos2912** [comment]
Hi, for now i solve this using nodemon, i'm not using the 'adonis serve --dev' anymore, with nodemon the problem stops.

**Comment by ugrinovsky** [comment]
killall node

**Comment by vahidForughi** [comment]
same problem , solved.
Hi, I have two terminal , once for `adonis serve --dev`  and anotherone for `adonis test` . I just kill adonis serve . now test working perfectly
