### ISSUE TITLE
auth.js is missing API type

### ISSUE THREAD

**Issue by thiagopinheirolima** [adonisjs/adonis-api-app#30]
If we check the constructor there is an API type for auth, and its missing when we start a new project.

**Comment by RomainLanz** [comment]
Hey @thiagopinheirolima! 👋 

Could you please elaborate on what's your issue?

**Comment by thiagopinheirolima** [comment]
When you use `adonis new project`  the file `auth.js` is missing the API (I'm sorry I misspelled) type.
If you look at adonis-app you will see the following code.
```
api: {
    serializer: 'Lucid',
    model: 'App/Model/Token',
    scheme: 'api'
  }
```

I think the code should be included at `adonis-api` also.

**Comment by RomainLanz** [comment]
`adonis-app` is an old boilerplate for 3.2 projects.

This section doesn't exist in `@adonisjs/auth` package.

**Comment by thiagopinheirolima** [comment]
Since its possible to use api-token as the auth schema, don't you think Its good to have it already included?
