### ISSUE TITLE
Why 'Adonis/Middleware/AuthInit' is not defined?

### ISSUE THREAD

**Issue by vincentducorps** [adonisjs/adonis-api-app#32]
There is any reason to not define 'Adonis/Middleware/AuthInit' in global middleware as is indicated in instructions?

https://github.com/adonisjs/adonis-api-app/blob/df3b661ec773bee947112034dc371434073cb557/start/kernel.js#L15

https://github.com/adonisjs/adonis-auth/blob/develop/instructions.md#register-global-middleware

https://adonisjs.com/docs/4.1/authentication#_registering_middleware

**Comment by RomainLanz** [comment]
Hey @vincentducorps! 👋 

Because this middleware would need the `session` package that is not installed by default by this blueprint.
