### ISSUE TITLE
Error responses in JSON

### ISSUE THREAD

**Issue by AaronVasquez** [adonisjs/adonis-api-app#38]
Some error responses such as `404` are returning HTML. Is there a setting to respond with JSON since this app is intended to be just an API?

**Comment by RomainLanz** [comment]
Hey @AaronVasquez! 👋 

Adonis use [Content Negotiation](https://adonisjs.com/docs/4.1/request#_content_negotiation) to know which format you want back.

Please, set correctly the `Accept` header to `application/json` if you want to receive JSON.

**Comment by AaronVasquez** [comment]
Hello, thanks for the quick reply. I am setting the header to `application/json`, but when the client gets an error response (for example, an incorrect route), it comes back as html. Is there middleware to make make the default return format json?

**Comment by Pixelartist** [comment]
In case someone is looking for a solution - https://github.com/adonisjs/adonis-framework/issues/919
Setting "Content-Type" doesnt help, needs to be "Accept".
